### ISSUE TITLE
HTML strings not escaped

### ISSUE THREAD

**Issue by laurence-myers** [clemos/try-haxe#110] opened 2016-07-07 10:57 UTC
I stumbled across this snippet:

[http://try.haxe.org/embed/730b9](http://try.haxe.org/embed/730b9)

Looks like this snippet has a string containing HTML; the HTML is getting rendered, instead of appearing as basic text.

Similar to #81.

**Comment by clemos** [comment] 2016-07-25 14:13
indeed, duplicate of #81, but thanks for the heads up :)

**Closed by clemos** 2016-07-25 14:13 UTC
